### ISSUE TITLE
non-image ngRepeat

### ISSUE THREAD

**Issue by konsumer** [funkhousr/angular-coverflow#2]
Hi, first I love the performance & usability of this project. Great work!

I have several "cards" that I want to display that are larger than your examples, and are not images, but divs with content.

My css looks like this:

``` css
.cards{
  width: 100%;
  -webkit-perspective: 900;
  overflow: hidden;
}

.card{
  position: absolute;
  top: 0;
  left: 0;
  box-shadow: 0px 0px 20px 0px rgba(255, 255, 255, .3);
  width: 365px;
  height: 510px;
}
```

I include `bower_components/angular-coverflow/coverflow.js` in my parent HTML, and `angular-coverflow` as app dependency.

In my controller:

``` javascript
$scope.coverflow = {};
$scope.cards = [
    {title: "card 1"},
    {title: "card 2"},
    {title: "card 3"},
    {title: "card 4"},
    {title: "card 5"},
    {title: "card 6"},
    {title: "card 7"},
    {title: "card 8"},
    {title: "card 9"},
    {title: "card 0"},
    {title: "card 1"},
    {title: "card 2"},
    {title: "card 3"},
    {title: "card 4"},
    {title: "card 5"},
    {title: "card 6"},
    {title: "card 7"},
    {title: "card 8"},
    {title: "card 9"},
    {title: "card 0"},
];
```

my template looks like this:

``` html
<coverflow class="cards" coverflow="coverflow" images="cards">
  <div ng-repeat="card in cards" class="card">
    {{ card.title }}
  </div>
</coverflow>
```

At this point I get an error:

```
TypeError: Cannot read property 'style' of undefined
    at Cover.updateCover (http://localhost:9000/bower_components/angular-coverflow/coverflow.js:76:18)
```

I am assuming it's because there are inline background image css things in there, and I am filling in my own covers with ngRepeat.

I am not sure how to continue. Any suggestions?
